name: 'Install dependencies'
description: 'Installs all required dependencies'
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
      with:
        repository: 'mtararujs/python-greetings'
        ref: 'main'
        fetch-depth: 1
    - name: Print step name
      run: echo "Installing all required python dependencies..."
      shell: cmd
    - name: List directory items
      run: dir
      shell: cmd
    - name: Install dependencies
      run: pip install -r requirements.txt
      shell: cmd
