name: 'Install dependencies'
description: 'Installs all required dependencies'
runs:
  using: 'composite'
  steps:
    - name: Print step name
      run: echo "Installing all required python dependencies..."
      shell: cmd
    - name: List directory items
      run: dir
      shell: cmd
    - name: Install dependencies
      run: pip install -r requirements.txt
      shell: cmd
